select * from customer limit 5
-- what is the total revenue generated by male vs  female customers?

select gender, sum(purchase_amount) as revenue from customer 
group by gender order by revenue desc

-- which customers use discount and still spent more then average 

select customer_id ,purchase_amount ,average_amount from (
select customer_id ,purchase_amount , round(avg(purchase_amount) over(),2)as average_amount ,discount_applied from customer )t
where purchase_amount>average_amount

--which are the top 5 products with higest average rating 

select item_purchased, round(avg(review_rating::numeric),2) as avg_review from customer 
group by item_purchased order by avg_review desc limit(5)

--compare the average purchase amount between standard and express shipping
select shipping_type,round(avg(purchase_amount),2) as average_price from customer
where shipping_type in ('Standard','Express')
group by shipping_type
order by average_price desc
-- total revenue between subscriber and non subscriber  and also the subscriber spen more then average or not 
select subscription_status,count(customer_id),
round(avg(purchase_amount),2)as average_amount,sum(purchase_amount) as sum_amount 
from customer group by subscription_status order by average_amount desc

-- which top 5 product have highest percentage of purchasing with discount applied
select item_purchased,round(sum(case when discount_applied='Yes' then 1 else 0 end )*100/count(*),2) as high_chance from customer
group by item_purchased order by high_chance desc limit 5

-- segment customer into new ,returning and loyals based on their previous purchase 
with segment as (
select customer_id,previous_purchases,case when previous_purchases=1 then 'new'
when previous_purchases between 1 and 10 then 'returner' else 'loyal' end 
as customer_return_count from customer 
)
-- select * from segment
select customer_return_count ,count(customer_id) as total_customer from segment 
group by customer_return_count order by total_customer desc

-- what are the top 3 item in each categary 
with top_item as (
select item_purchased,category,count(customer_id) as total_order, 
row_number() over(partition by category order by count(customer_id)  desc) as item_rank
from customer
group by category,item_purchased
)

select item_rank,category,item_purchased,total_order from top_item where item_rank<=3

-- are customer who repeted are likly subscriber as well 
select subscription_status,count(customer_id) as subscriber from customer 
where feqently_purchase > 5 group by subscription_status order by subscriber asc

-- check the revnue by age group 
select age_group,sum(purchase_amount) as revenue from customer group by age_group order by revenue desc


